# Copyright The Notary Project Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: License Checker

on:
  push:
    branches: 
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: write
  pull-requests: write

jobs:
  check-license:
    if: github.repository == 'notaryproject/notation-go'
    uses: notaryproject/notation-core-go/.github/workflows/reusable-license-checker.yml@main
  fork-check-license:
    if: github.repository == 'yizha1/notation-go'
    uses: yizha1/notation-core-go/.github/workflows/reusable-license-checker.yml@03171674c94728622c5b1534b5e3396fcb468733